project:
  type: website
  title: "Verknüpfte Offene Ausstellung"
  output-dir: docs

format:
  revealjs:
    theme: default
    slide-number: true
    transition: slide
    background-transition: fade
    incremental: false
    footer: "CC BY-SA 4.0"    
    css: styles.css