project:
  type: website
  title: "Verknüpfte Offene Ausstellung"
  output-dir: _output

format:
  revealjs:
    theme: default
    slide-number: true
    transition: slide
    background-transition: fade
    incremental: false
